<a href="https://colab.research.google.com/github/Varshashri1505/PythonBasics/blob/main/Complete_numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy - Numerical Python

Advantages of Numpy Arrays

1. Allows several Mathematical Operations

2. Faster Operations

In [1]:
import numpy as np

List VS Numpy - Time Taken

In [3]:
from time import process_time

Time taken by a list

In [4]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0006198330000000141


Time taken by a Numpy

In [8]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)


0.00016004299999927696


Numpy Arrays

In [9]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [10]:
#numpy
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [11]:
#creating a 1D array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [12]:
a.shape

(4,)

In [14]:
#creating a 2D array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
b.shape #rows & columns

(2, 4)

In [16]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [18]:
# create a numpy array of zeros
x = np.zeros((4,5)) #use paranthesis for shape
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
# create a numpy array of ones
y = np.ones((4,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
#create a numpy array with particular array
z = np.full((5,4),5) #shape with required number
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [24]:
# create an identity matrix
a = np.eye(5)
print(a)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
#create a numpy array with randam values
b = np.random.random((3,4)) # numbers will be between 0 & 1
print(b)

[[0.29646986 0.56219021 0.02231898 0.9992426 ]
 [0.06257618 0.54373531 0.08988346 0.9289574 ]
 [0.82684294 0.00340762 0.42985756 0.65980884]]


In [33]:
# random onnteger values array within a specific range
c = np.random.randint(10,100,(3,5)) #mention range then the shape
print(c)

[[91 30 67 68 14]
 [75 91 94 57 15]
 [45 82 46 47 56]]


In [34]:
# create an array of evenly spaced values --> specifying number of values required
d = np.linspace(10,30,5) # start, end, range
print(d)

[10. 15. 20. 25. 30.]


In [35]:
#array of evenly spaced values --> specify the step
e = np.arange(10,30,5) # start, end, step
print(e)

[10 15 20 25]


In [36]:
# convert list to numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [37]:
c = np.random.randint(10,90,(5,5))
print(c)

[[42 61 39 60 78]
 [78 53 29 18 42]
 [46 75 19 88 59]
 [83 20 59 58 67]
 [79 44 59 40 51]]


In [38]:
# array dimension
print(c.shape)

(5, 5)


In [39]:
# no: dimensions
print(c.ndim)

2


In [40]:
#check no:elements in array
print(c.size)

25


In [41]:
# check datatypes of values in the array
print(c.dtype)

int64


Mathematical Operators on np array

In [42]:
#list using '+'
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # concatinate two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [43]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [44]:
print(a)
print(b)

[[0 3 0]
 [8 7 6]
 [5 9 1]]
[[19 15 14]
 [17 11 12]
 [18 13 17]]


In [47]:
print(a+b) #in numpy we use '+' to add
print(a-b) #||
print(a*b) #||
print(a/b) #||

[[19 18 14]
 [25 18 18]
 [23 22 18]]
[[-19 -12 -14]
 [ -9  -4  -6]
 [-13  -4 -16]]
[[  0  45   0]
 [136  77  72]
 [ 90 117  17]]
[[0.         0.2        0.        ]
 [0.47058824 0.63636364 0.5       ]
 [0.27777778 0.69230769 0.05882353]]


In [50]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[19 18 14]
 [25 18 18]
 [23 22 18]]
[[-19 -12 -14]
 [ -9  -4  -6]
 [-13  -4 -16]]
[[  0  45   0]
 [136  77  72]
 [ 90 117  17]]
[[0.         0.2        0.        ]
 [0.47058824 0.63636364 0.5       ]
 [0.27777778 0.69230769 0.05882353]]


Array Manipulation

In [52]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 7 3]
 [0 6 3]]
(2, 3)


In [53]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[3 0]
 [7 6]
 [3 3]]
(3, 2)


In [54]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 3 7]
 [0 4 9]]
(2, 3)


In [55]:
#another way of transpose
trans2 = array.T
print(trans2)
print(trans2.shape)

[[4 0]
 [3 4]
 [7 9]]
(3, 2)


In [56]:
# reshaping array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[5 3 9]
 [9 4 0]]
(2, 3)


In [57]:
#now
b = a.reshape(3,2)
print(b)
print(b.shape)

[[5 3]
 [9 9]
 [4 0]]
(3, 2)
